# Generated by Django 3.0 on 2022-09-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('brand', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptop'), ('TV', 'Television'), ('WM', 'WashingMachine')], max_length=2)),
            ],
        ),
    ]
